### ISSUE TITLE
Add support for Windows and macOS?

### ISSUE THREAD

**Issue by ma-sadeghi** [conda-forge/ocl-icd-system-feedstock#2]
Could you please add support for Windows and macOS?

**Comment by jaimergp** [comment]
AFAIK the ICD discovery mechanisms are different in those platforms. For MacOS, maybe you are looking for https://anaconda.org/conda-forge/ocl_icd_wrapper_apple. On Windows there's no such thing, I think.

**Comment by ma-sadeghi** [comment]
Great, thanks. I know this is not the right place to ask, but just in case you know how to deal with it: I'm trying to install `pyopencl` on Windows, but upon importing (`import pyopencl`) I get:
```python
...
    from pyopencl._cl import bitlog2  # noqa: F401
ImportError: DLL load failed while importing _cl: The specified procedure could not be found.
```
On Linux, I was able to solve this by installing `ocl-icd-system`, but as you mentioned, there's a different mechanism on Windows. Do you know how to fix this by any chance?

Anyway, thanks for your input, and feel free to close this issue.

**Comment by jaimergp** [comment]
On Windows, `pyopencl` depends on `khronos-opencl-icd-loader`, so you should be covered. This is the loader, but you need an OpenCL _implementation_. This can be obtained via your GPU vendor (as Nvidia does through their drivers), or using projects such as `oclgrind`. I don't think the Khronos loader is unable to see the system's installation on Windows. If that's the case, an issue should be raised at https://github.com/conda-forge/khronos-opencl-icd-loader-feedstock/issues.

**Comment by isuruf** [comment]
Are you sure you had the same error on Linux?

**Comment by ma-sadeghi** [comment]
@isuruf It was a while ago. I just tried to reproduce the issue on my Linux installation and I can't seem to be able to. I think it's all good then.

Just a quick question: when I installed a fresh copy of `pyopencl` on my Linux machine, I got the following warning:
```bash
WARNING: No ICDs were found. Either,
- Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or
- Make your system-wide implementation visible by installing ocl-icd-system conda package.
```

Could you please elaborate the difference between the two options? I'd really appreciate it.

Many thanks!

**Comment by isuruf** [comment]
See https://documen.tician.de/pyopencl/misc.html and let me know if you need more clarification
